# Source: nginx-ingress-controller/templates/controller-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress
  namespace: ingress
  labels:
    app.kubernetes.io/name: nginx-ingress
data:
  use-forwarded-headers: "true"
