apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-default-backend
  namespace: ingress
  labels:
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/component: default-backend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/component: default-backend
