apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-metrics
  namespace: "default"
  labels:
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/component: metrics
  # annotations:
  #   prometheus.io/port: '9913'
  #   prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9913
      targetPort: metrics
  selector:
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/component: controller
