# Source: nginx-ingress-controller/templates/controller-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: ingress
  labels:
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/component: controller
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.100
  externalTrafficPolicy: Local
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
  selector:
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/component: controller
