apiVersion: v1
kind: PersistentVolume
metadata:
  name: media
spec:
  capacity:
    storage: 4Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /volume1/media/
    server: 192.168.1.240
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: cavern
spec:
  volumeName: media
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Ti
