apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-sonarr
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /volume1/config/sonarr
    server: 192.168.1.240
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-sonarr
  namespace: cavern
spec:
  volumeName: config-sonarr
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
