apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin
  namespace: cavern
  labels:
    app: jellyfin
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/enable-access-log: "false"
spec:
  rules:
  - host: jelly.h.valmil.net
    http:
      paths:
      - backend:
          service:
            name: jellyfin
            port:
              name: http
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - "jelly.h.valmil.net"
    secretName: jellyfin-tls
