apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: cavern
  labels:
    app: jellyfin
spec:
  type: ClusterIP
  ports:
  - name: http
    targetPort: http
    port: 8096
    protocol: TCP
  selector:
    app: jellyfin
