apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: memberlist
  namespace: metallb-system
spec:
  encryptedData:
    secretkey: AgBByn4kXfLdBSApxRf5Rh3c+FtYqQQdXVY2gxGj15fofd5TSFdg4D8WjEiK8YYeHZmuntnSy99Hs73i8cNdiMxUi5axGuPQ0hgEbGFf+GDfSvOOYrkLKWeun4zJ9I+e1C0Il28iJHwsPi7BLjvyjuL514XMEqBO6qZe3m+2qoLqRvxg9mlezMS1g2npiTYN1au/tsmdKUbAi80l2RqQiSrjcditpB/v66TZ2e33n9vwit3PExBwVEYxF5mbiVtjUh0uzqgKDmEBYMG/RUaxUYheKoQHK/eOnKIhUAespf9BPvaqBKQZtEQmnLvN1Dt7ee7YocdmajV/ubvjivEbYVrRG6P/9n8GhaCYJSwqBXPZ9lpBdi2fivutLc/z0bOLQNEXI6MVemVIobCToFTesnujDeHLyVYz7riFrVQtqqBDzatcrcg5sLtuXrMPrWtp1JRthsdxEDevjwUrjlm5sdkOyPKNFf6pQcp/n6DxEH7LPxgaYa5uXLZtnjLAq+rwhEOBPxhbJAbstIEgGVKg437j2/6dylB6oAifj2khzt7n86VLiOSGmMJk22dsP+h0jKm6R+QwUIeRoL7E52T05kFGgCjysDFRpGq8t5E2pgUiWsovDFkaprdmtJWRCoWFMFatmi9+7LcRJr/Yl4zpIsWDb8YYkJszRHewxvTJ0VYhpPFUa8VQdZrLBv4oNoI1DwDHL2srVw5veIKRWgutt7RcPtKrIiIn/mWfCy7uDcTBzbTvQpcT05a5GRJCByS1BSz+xB+G9k3RtvmzZcfLkKDP1EMbb63+rTZFR6xwbQ1Pi77DGI8Xq7mC/hcu/lAAI4iR3FPh+f2NDDbfXgSYf7q0fUb3KZg8kF1iV0ExnlLw2fNFlXS6VNdYUXNEpZH82Vo4XOBkX9Ywxa5pZR2qSOzw0DwmIqwfwvYj94AFbUA=
  template:
    metadata:
      creationTimestamp: null
      name: memberlist
      namespace: metallb-system

