apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarr-jellyfin-script
  namespace: cavern
data:
  refresh-jellyfin.sh: |
    #!/bin/sh
    curl -sv http://jellyfin:8096/library/refresh?api_key=$JELLYFIN_API_KEY
